# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY products.json .
COPY settings.py .
COPY import_data.py .

# Specify the command to run the script
CMD ["python", "import_data.py"]
